turing_garden = Garden.create!(name: 'Turing Community Garden', organic: true)
library_garden = Garden.create!(name: 'Public Library Garden', organic: true)
other_garden = Garden.create!(name: 'Main Street Garden', organic: false)

turing_garden.plots.create!(number: 25, size: "Large", direction: "East")
turing_garden.plots.create!(number: 26, size: "Small", direction: "West")
library_garden.plots.create!(number: 2, size: "Small", direction: "South")
other_garden.plots.create!(number: 738, size: "Medium", direction: "West")

ben_plot = turing_garden.plots.create!(number: 25, size: "Large", direction: "East")
mike_plot = turing_garden.plots.create!(number: 26, size: "Small", direction: "West")
andre_plot = library_garden.plots.create!(number: 2, size: "Small", direction: "South")
chris_plot = other_garden.plots.create!(number: 738, size: "Medium", direction: "West")

cactus = Plant.create!(name: "Cactus", description: "It's just a cactus", days_to_harvest: 1)
squash = Plant.create!(name: "Squash", description: "A tasty squash", days_to_harvest: 2)
cucumber = Plant.create!(name: "Cucumber", description: "Good for pickling", days_to_harvest: 3)
pumpkin = Plant.create!(name: "Pumpkin", description: "Big, orange, and round", days_to_harvest: 4)
watermelon = Plant.create!(name: "Watermelon", description: "Big, green, red inside", days_to_harvest: 5)

PlotPlant.create!(plot_id: ben_plot.id , plant_id: cactus.id)
PlotPlant.create!(plot_id: ben_plot.id , plant_id: squash.id)
PlotPlant.create!(plot_id: mike_plot.id , plant_id: cucumber.id)
PlotPlant.create!(plot_id: andre_plot.id , plant_id: pumpkin.id)
PlotPlant.create!(plot_id: chris_plot.id , plant_id: pumpkin.id)
PlotPlant.create!(plot_id: chris_plot.id , plant_id: cactus.id)
